### ISSUE TITLE
mu.interpolated_recording not compatible with spikeinterface lattest version 0.101.0

### ISSUE THREAD

**Issue by David-H-Chang** [evarol/dredge#1]
Hey, I found   InterpolateMotionRecording in new version of spikeinterface requires motion object as one of the variable, not just a numpy array as displacement.T. Also, border_mode are set to default and there are some errors passing the parameters in mu.interpolated_recording.

Here are my codes:
```python
rec = mu.get_interpolated_recording(me_rigid_upsampled, rec)
rec
```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[15], line 1
----> 1 rec = mu.get_interpolated_recording(me_rigid_upsampled, rec)
      2 rec

File /share/home/zhangdaohan20h/dredge-main/python/dredge/motion_util.py:400, in get_interpolated_recording(motion_est, recording, border_mode)
    397     assert displacement.ndim == 2 and displacement.shape[0] == 2
    399 # now we can use correct_motion
--> 400 rec_interpolated = InterpolateMotionRecording(
    401     rec,
    402     displacement.T,
    403     temporal_bins,
    404     spatial_bins,
    405     #border_mode=border_mode, updated by zdh
    406 )
    407 return rec_interpolated

File ~/.conda/envs/kilosort4/lib/python3.9/site-packages/spikeinterface/sortingcomponents/motion/motion_interpolation.py:326, in InterpolateMotionRecording.__init__(self, recording, motion, border_mode, spatial_interpolation_method, sigma_um, p, num_closest, interpolation_time_bin_centers_s, interpolation_time_bin_size_s, dtype, **spatial_interpolation_kwargs)
    301 channel_locations = recording.get_channel_locations()
    302 '''
    303 import json #This is my testing codes 
    304 #print(motion.keys())#
   (...)
    324     print(f'Dimension attribute: {motion.dim}')  
    325 '''
--> 326 assert channel_locations.ndim >= motion.dim, (
    327     f"'direction' {motion.direction} not available. "
    328     f"Channel locations have {channel_locations.ndim} dimensions."
    329 )
    330 spatial_interpolation_kwargs = dict(
    331     sigma_um=sigma_um, p=p, num_closest=num_closest, **spatial_interpolation_kwargs
    332 )
    333 if border_mode == "remove_channels":

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

**Comment by cwindolf** [comment]
Hi @DaohanZhang , thanks again for opening this issue. I just pushed a commit to the main branch which seems to fix this problem (tested in the demo LFP notebook). Would you be able to try it out on your end and let me know if you have more problems?

**Comment by DaohanZhang** [comment]
Thanks a lot Charlie! The part in the notebook seems okay! But the same issue raised after I put the rec into kilosor4.
```python
sorting = ss.run_sorter(sorter_name="kilosort4", recording=rec, docker_image=False, remove_existing_folder=True, delete_output_folder = False,
                        torch_device=("cuda:0"), verbose=True)
sorting
```
```
========================================
Loading recording with SpikeInterface...
number of samples: 1800000
Error running kilosort4
---------------------------------------------------------------------------
SpikeSortingError                         Traceback (most recent call last)
Cell In[46], line 4
      1 #sorting_KS2 = ss.run_sorter(sorter_name="kilosort2", recording=rec, docker_image=True, verbose=True)
      2 #import docker
      3 print('#')
----> 4 sorting = ss.run_sorter(sorter_name="kilosort4", recording=rec, docker_image=False, remove_existing_folder=True, delete_output_folder = False,
      5                         torch_device=("cuda:0"), verbose=True)
      6 sorting

File ~/.conda/envs/kilosort4/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py:216, in run_sorter(sorter_name, recording, folder, remove_existing_folder, delete_output_folder, verbose, raise_error, docker_image, singularity_image, delete_container_files, with_output, output_folder, **sorter_params)
    205             raise RuntimeError(
    206                 "The python `spython` package must be installed to "
    207                 "run singularity. Install with `pip install spython`"
    208             )
    210     return run_sorter_container(
    211         container_image=container_image,
    212         mode=mode,
    213         **common_kwargs,
    214     )
--> 216 return run_sorter_local(**common_kwargs)

File ~/.conda/envs/kilosort4/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py:276, in run_sorter_local(sorter_name, recording, folder, remove_existing_folder, delete_output_folder, verbose, raise_error, with_output, output_folder, **sorter_params)
    274 SorterClass.set_params_to_folder(recording, folder, sorter_params, verbose)
    275 SorterClass.setup_recording(recording, folder, verbose=verbose)
--> 276 SorterClass.run_from_folder(folder, raise_error, verbose)
    277 if with_output:
    278     sorting = SorterClass.get_result_from_folder(folder, register_recording=True, sorting_info=True)

File ~/.conda/envs/kilosort4/lib/python3.9/site-packages/spikeinterface/sorters/basesorter.py:301, in BaseSorter.run_from_folder(cls, output_folder, raise_error, verbose)
    298         print(f"{sorter_name} run time {run_time:0.2f}s")
    300 if has_error and raise_error:
--> 301     raise SpikeSortingError(
    302         f"Spike sorting error trace:\n{error_log_to_display}\n"
    303         f"Spike sorting failed. You can inspect the runtime trace in {output_folder}/spikeinterface_log.json."
    304     )
    306 return run_time

SpikeSortingError: Spike sorting error trace:
Traceback (most recent call last):
  File "/home/zhangdaohan20h/.conda/envs/kilosort4/lib/python3.9/site-packages/spikeinterface/sorters/basesorter.py", line 261, in run_from_folder
    SorterClass._run_from_folder(sorter_output_folder, sorter_params, verbose)
  File "/home/zhangdaohan20h/.conda/envs/kilosort4/lib/python3.9/site-packages/spikeinterface/sorters/external/kilosort4.py", line 184, in _run_from_folder
    file_object = RecordingExtractorAsArray(recording)
  File "/home/zhangdaohan20h/.conda/envs/kilosort4/lib/python3.9/site-packages/kilosort/io.py", line 853, in __init__
    self.c = self.recording.get_traces(start_frame=0, end_frame=1, segment_index=0).shape[1]
  File "/home/zhangdaohan20h/.conda/envs/kilosort4/lib/python3.9/site-packages/spikeinterface/core/baserecording.py", line 342, in get_traces
    traces = rs.get_traces(start_frame=start_frame, end_frame=end_frame, channel_indices=channel_indices)
  File "/home/zhangdaohan20h/.conda/envs/kilosort4/lib/python3.9/site-packages/spikeinterface/sortingcomponents/motion/motion_interpolation.py", line 467, in get_traces
    traces = interpolate_motion_on_traces(
  File "/home/zhangdaohan20h/.conda/envs/kilosort4/lib/python3.9/site-packages/spikeinterface/sortingcomponents/motion/motion_interpolation.py", line 139, in interpolate_motion_on_traces
    bin_time = time_bins[bin_ind]
IndexError: index 1800000 is out of bounds for axis 0 with size 1800000

Spike sorting failed. You can inspect the runtime trace in /share/home/zhangdaohan20h/CODES/NPX/preanalysis/kilosort4_output/spikeinterface_log.json.
```
It is similar to what i have reported in https://github.com/SpikeInterface/spikeinterface/issues/3328
1800000 is the number of time steps in this 60s clip

**Comment by DaohanZhang** [comment]
![image](https://github.com/user-attachments/assets/057de827-ba43-4c20-8c94-a8e439b2ee9e)
Here are contents in kilosort4_output/spikeinterface_log.json

**Comment by DaohanZhang** [comment]
@cwindolf It did work! But a 1min recording cost me approximately 2 days to finish the sorting process. I m still figuring out the reason. Do you have any ideas?

**Comment by cwindolf** [comment]
Hi @DaohanZhang , sorry, somehow I missed this! It should definitely be faster than that.

I wonder -- I may be misremembering, but did you mention resampling the motion estimate to the recording's sampling frequency? In other words, if motion was originally estimated at 250Hz, did you resample the motion estimate to the full 30kHz? I would expect this to drastically slow things down, since separate interpolation matrices would be computed for all time steps. If that's the case, I'd suggest not doing that -- you can leave the motion at 250Hz and that will still be a pretty rapid motion correction.

Let me know if what I've guessed there is inaccurate -- I can offer more suggestions if so.

**Comment by cwindolf** [comment]
I see... okay, sorry to be asking for so many things, but can you try one last thing? Could you try doing
```
rec_interpolated = rec_interpolated.save_to_folder("some folder on your computer", n_jobs=your_preferred_n_jobs)
```
I think that this may be a simpler way to trigger the error, in which case it'll be easier to test.

**Comment by DaohanZhang** [comment]
Oh, I have put my detailed information above! Maybe it is also helpful!

**Comment by DaohanZhang** [comment]
> I see... okay, sorry to be asking for so many things, but can you try one last thing? Could you try doing
> 
> ```
> rec_interpolated = rec_interpolated.save_to_folder("some folder on your computer", n_jobs=your_preferred_n_jobs)
> ```
> 
> I think that this may be a simpler way to trigger the error, in which case it'll be easier to test.

Indeed! This is the first time I found this series of motion correction issues.
Here are the results:
```python
rec_interpolated = rec_interpolated.save_to_folder("/home/zhangdaohan20h/CODES/NPX/HS104-2/rec_inter", 
                                                   n_jobs=20)
```
```
Use cache_folder=/home/zhangdaohan20h/CODES/NPX/HS104-2/rec_inter
write_binary_recording 
n_jobs=20 - samples_per_chunk=30,000 - chunk_memory=34.22 MiB - total_memory=684.36 MiB - chunk_duration=1.00s
write_binary_recording: 100%|█████████▉| 594/595 [07:31<00:00,  1.32it/s]
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/zhangdaohan20h/.conda/envs/kilosort4/lib/python3.9/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/zhangdaohan20h/.conda/envs/kilosort4/lib/python3.9/concurrent/futures/process.py", line 205, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/zhangdaohan20h/.conda/envs/kilosort4/lib/python3.9/concurrent/futures/process.py", line 205, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/zhangdaohan20h/.conda/envs/kilosort4/lib/python3.9/site-packages/spikeinterface/core/job_tools.py", line 463, in function_wrapper
    return _func(segment_index, start_frame, end_frame, _worker_ctx)
  File "/home/zhangdaohan20h/.conda/envs/kilosort4/lib/python3.9/site-packages/spikeinterface/core/recording_tools.py", line 179, in _write_binary_chunk
    traces = recording.get_traces(
  File "/home/zhangdaohan20h/.conda/envs/kilosort4/lib/python3.9/site-packages/spikeinterface/core/baserecording.py", line 342, in get_traces
    traces = rs.get_traces(start_frame=start_frame, end_frame=end_frame, channel_indices=channel_indices)
  File "/home/zhangdaohan20h/.conda/envs/kilosort4/lib/python3.9/site-packages/spikeinterface/sortingcomponents/motion/motion_interpolation.py", line 467, in get_traces
    traces = interpolate_motion_on_traces(
  File "/home/zhangdaohan20h/.conda/envs/kilosort4/lib/python3.9/site-packages/spikeinterface/sortingcomponents/motion/motion_interpolation.py", line 139, in interpolate_motion_on_traces
    bin_time = time_bins[bin_ind]
IndexError: index 29701 is out of bounds for axis 0 with size 29701
"""

The above exception was the direct cause of the following exception:

IndexError                                Traceback (most recent call last)
Cell In[49], line 1
----> 1 rec_interpolated = rec_interpolated.save_to_folder("/home/zhangdaohan20h/CODES/NPX/HS104-2/rec_inter", n_jobs=20)

File ~/.conda/envs/kilosort4/lib/python3.9/site-packages/spikeinterface/core/base.py:970, in BaseExtractor.save_to_folder(self, name, folder, overwrite, verbose, **save_kwargs)
    967 self.save_metadata_to_folder(folder)
    969 # save data (done the subclass)
--> 970 cached = self._save(folder=folder, verbose=verbose, **save_kwargs)
    972 # copy properties/
    973 self.copy_metadata(cached)

File ~/.conda/envs/kilosort4/lib/python3.9/site-packages/spikeinterface/core/baserecording.py:537, in BaseRecording._save(self, format, verbose, **save_kwargs)
    534 dtype = kwargs.get("dtype", None) or self.get_dtype()
    535 t_starts = self._get_t_starts()
--> 537 write_binary_recording(self, file_paths=file_paths, dtype=dtype, verbose=verbose, **job_kwargs)
    539 from .binaryrecordingextractor import BinaryRecordingExtractor
    541 # This is created so it can be saved as json because the `BinaryFolderRecording` requires it loading
    542 # See the __init__ of `BinaryFolderRecording`

File ~/.conda/envs/kilosort4/lib/python3.9/site-packages/spikeinterface/core/recording_tools.py:146, in write_binary_recording(recording, file_paths, dtype, add_file_extension, byte_offset, auto_cast_uint, verbose, **job_kwargs)
    142 init_args = (recording, file_path_dict, dtype, byte_offset, cast_unsigned)
    143 executor = ChunkRecordingExecutor(
    144     recording, func, init_func, init_args, job_name="write_binary_recording", verbose=verbose, **job_kwargs
    145 )
--> 146 executor.run()

File ~/.conda/envs/kilosort4/lib/python3.9/site-packages/spikeinterface/core/job_tools.py:425, in ChunkRecordingExecutor.run(self)
    422 if self.progress_bar:
    423     results = tqdm(results, desc=self.job_name, total=len(all_chunks))
--> 425 for res in results:
    426     if self.handle_returns:
    427         returns.append(res)

File ~/.conda/envs/kilosort4/lib/python3.9/site-packages/tqdm/std.py:1181, in tqdm.__iter__(self)
   1178 time = self._time
   1180 try:
-> 1181     for obj in iterable:
   1182         yield obj
   1183         # Update and possibly print the progressbar.
   1184         # Note: does not call self.update(1) for speed optimisation.

File ~/.conda/envs/kilosort4/lib/python3.9/concurrent/futures/process.py:562, in _chain_from_iterable_of_lists(iterable)
    556 def _chain_from_iterable_of_lists(iterable):
    557     """
    558     Specialized implementation of itertools.chain.from_iterable.
    559     Each item in *iterable* should be a list.  This function is
    560     careful not to keep references to yielded objects.
    561     """
--> 562     for element in iterable:
    563         element.reverse()
    564         while element:

File ~/.conda/envs/kilosort4/lib/python3.9/concurrent/futures/_base.py:609, in Executor.map.<locals>.result_iterator()
    606 while fs:
    607     # Careful not to keep a reference to the popped future
    608     if timeout is None:
--> 609         yield fs.pop().result()
    610     else:
    611         yield fs.pop().result(end_time - time.monotonic())

File ~/.conda/envs/kilosort4/lib/python3.9/concurrent/futures/_base.py:439, in Future.result(self, timeout)
    437     raise CancelledError()
    438 elif self._state == FINISHED:
--> 439     return self.__get_result()
    441 self._condition.wait(timeout)
    443 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File ~/.conda/envs/kilosort4/lib/python3.9/concurrent/futures/_base.py:391, in Future.__get_result(self)
    389 if self._exception:
    390     try:
--> 391         raise self._exception
    392     finally:
    393         # Break a reference cycle with the exception in self._exception
    394         self = None

IndexError: index 29701 is out of bounds for axis 0 with size 29701
```

**Comment by DaohanZhang** [comment]
Do i need to open a new issue in spikeGLX? I guess it is the problem there.

**Comment by cwindolf** [comment]
It's not a spikeGLX problem, it's either my fault or in spikeinterface. I should be able to investigate early next week!

**Comment by DaohanZhang** [comment]
Oh, that's a typo! Thank you very much!

**Comment by cwindolf** [comment]
Hi @DaohanZhang , just mentioning here that the latest commits to dredge and the pull request linked right above this comment should hopefully fix this issue! Thanks again for all of your help figuring it out and for reporting it.
